name: walking_companion
description: Arabic offline walking and movement companion with background tracking.
publish_to: "none"

version: 4.0.0+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
