name: dashcam_no_audio
description: Offline Android dash cam app - video only, no audio, with burned-in timestamp.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  geolocator: ^13.0.2
  video_player: ^2.9.2
  intl: ^0.19.0
  share_plus: ^11.0.0
  ffmpeg_kit_flutter_new: ^4.1.0
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
