plugins { id 'com.android.application' }

android {
    namespace 'com.explapp.walklegacy'
    compileSdk 33
    defaultConfig {
        applicationId 'com.explapp.walklegacy'
        minSdk 19
        targetSdk 28
        versionCode 5
        versionName '3.2.0-legacy'
    }
    buildTypes { release { minifyEnabled false } }
    lintOptions { abortOnError true; disable 'ExpiredTargetSdkVersion' }
}
